### ISSUE TITLE
Leak and Undefined behaviour

### ISSUE THREAD

**Issue by Hazurl** [Jackojc/Lithe#5]
https://github.com/Jackojc/Lithe/blob/09c4cca9515cdad1e8eeffa86ff5c583886b8a46/src/world/world.cpp#L17

You call `new` in the `create_system` method, but you never delete the system.
Also, `std::find` can returns  an iterator to `end()`, which will result in UB if the system doesn't exists.

Time to use `std::unique_ptr` ? ;)

**Comment by Jackojc** [comment]
Fixed in 1d7a662 by usage of std::unique_ptr. Thanks for the help as always Hazurl!
